name: Smoke Tests on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run smoke tests
      run: npx cypress run --env TAGS='@smoke'
